# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib import pyplot as plt
import numpy as np
from skimage.color import rgb2gray
from math import sqrt
from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QSlider

from PyQt5 import QtCore, QtGui, QtWidgets,uic
from PyQt5.QtWidgets import QMainWindow , QApplication , QLabel 
from pyqtgraph import ImageView 
import matplotlib
matplotlib.use('Qt5Agg')

from PyQt5 import QtCore, QtWidgets

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure

class MplCanvas(FigureCanvasQTAgg):
    
    def __init__(self, parent=None):
        fig = Figure()
        self.axes = fig.add_axes([0,0,1,1])
        super(MplCanvas, self).__init__(fig)
        #fig.tight_layout()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 519)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 81);\n"
"border-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.verticalLayout_mainlable = QtWidgets.QVBoxLayout()
        self.verticalLayout_mainlable.setObjectName("verticalLayout_mainlable")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_mainlable.addItem(spacerItem)
        self.mainimage = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mainimage.setFont(font)
        self.mainimage.setStyleSheet("background-color: rgb(86, 86, 129);")
        self.mainimage.setObjectName("mainimage")
        self.verticalLayout_mainlable.addWidget(self.mainimage)
        self.verticalLayout_main.addLayout(self.verticalLayout_mainlable)

        self.fig = Figure()
        self.image_canvas = FigureCanvasQTAgg(self.fig)
        self.verticalLayout_main.addWidget(self.image_canvas)
       
        
        #self.verticalLayout_main.addWidget(self.sc)

        self.horizontalLayout_combobox = QtWidgets.QHBoxLayout()
        self.horizontalLayout_combobox.setObjectName("horizontalLayout_combobox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_choosefilter = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_choosefilter.setFont(font)
        self.label_choosefilter.setObjectName("label_choosefilter")
        self.verticalLayout_2.addWidget(self.label_choosefilter)
        self.choosedomain = QtWidgets.QComboBox(self.centralwidget)
        self.choosedomain.setStyleSheet("background-color: rgb(86, 86, 129);")
        self.choosedomain.setObjectName("choosedomain")
        self.choosedomain.addItem("")
        self.choosedomain.addItem("")
        self.choosedomain.addItem("")
        self.choosedomain.addItem("")
        self.verticalLayout_2.addWidget(self.choosedomain)
        self.horizontalLayout_combobox.addLayout(self.verticalLayout_2)
        self.verticalLayout_domain = QtWidgets.QVBoxLayout()
        self.verticalLayout_domain.setObjectName("verticalLayout_domain")
        self.label_choosedomain = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_choosedomain.setFont(font)
        self.label_choosedomain.setObjectName("label_choosedomain")
        self.verticalLayout_domain.addWidget(self.label_choosedomain)
        self.choosefilter = QtWidgets.QComboBox(self.centralwidget)
        self.choosefilter.setStyleSheet("background-color: rgb(86, 86, 129);")
        self.choosefilter.setObjectName("choosedomain")
        self.choosefilter.addItem("")
        self.choosefilter.addItem("")
        self.choosefilter.addItem("")
        self.choosefilter.addItem("")
        self.choosefilter.addItem("")
        self.choosefilter.addItem("")
        
        self.verticalLayout_domain.addWidget(self.choosefilter)
        self.horizontalLayout_combobox.addLayout(self.verticalLayout_domain)
        self.verticalLayout_main.addLayout(self.horizontalLayout_combobox)
        self.outputimage_lable = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.outputimage_lable.setFont(font)
        self.outputimage_lable.setStyleSheet("background-color: rgb(86, 86, 129);")
        self.outputimage_lable.setObjectName("outputimage_lable")
        self.verticalLayout_main.addWidget(self.outputimage_lable)
        
        self.fig2 = Figure()
        self.image2_canvas = FigureCanvasQTAgg(self.fig2)
        self.verticalLayout_main.addWidget(self.image2_canvas)


        self.horizontalLayout.addLayout(self.verticalLayout_main)
        self.verticalLayout_gistogram = QtWidgets.QVBoxLayout()
        self.verticalLayout_gistogram.setObjectName("verticalLayout_gistogram")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_gistogram.addItem(spacerItem1)
        self.label_histogram = QtWidgets.QLabel(self.centralwidget)
        self.label_histogram.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_histogram.setFont(font)
        self.label_histogram.setStyleSheet("background-color: rgb(86, 86, 129);")
        self.label_histogram.setObjectName("label_histogram")
        self.verticalLayout_gistogram.addWidget(self.label_histogram)
        self.fig3 = Figure()
        self.image3_canvas = FigureCanvasQTAgg(self.fig3)
        self.verticalLayout_gistogram.addWidget(self.image3_canvas)

        
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_gistogram.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_gistogram.addItem(spacerItem3)
        self.label_filteredhisto = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_filteredhisto.setFont(font)
        self.label_filteredhisto.setStyleSheet("background-color: rgb(86, 86, 129);")
        self.label_filteredhisto.setObjectName("label_filteredhisto")
        self.verticalLayout_gistogram.addWidget(self.label_filteredhisto)
        self.fig4 = Figure()
        self.image4_canvas = FigureCanvasQTAgg(self.fig4)
        self.verticalLayout_gistogram.addWidget(self.image4_canvas)
        self.fig5 = Figure()
        self.image5_canvas = FigureCanvasQTAgg(self.fig5)
        self.verticalLayout_gistogram.addWidget(self.image5_canvas)
        self.horizontalLayout.addLayout(self.verticalLayout_gistogram)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setStyleSheet("color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.menuFile.setFont(font)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/open.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Task1 Image Processing"))
        self.mainimage.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400; color:#ffffff;\">Main Image</span></p></body></html>"))
        self.label_choosefilter.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Choose Domain</span></p></body></html>"))
        self.label_choosedomain.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Choose Filter</span></p></body></html>"))
        self.outputimage_lable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Filtered Image</span></p></body></html>"))
        self.label_histogram.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Histogram</span></p></body></html>"))
        self.label_filteredhisto.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\"> Histogram Image</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; color:#ffffff;\">Image processing</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.choosedomain.setItemText(1, _translate("MainWindow", " Frequancy Domain"))
        self.choosedomain.setItemText(2, _translate("MainWindow", " Spatial Domain"))
        self.choosedomain.setItemText(3, _translate("MainWindow", " Frequancy Domain RGB"))
        

